steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest || exit 0']
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}', '--cache-from', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'webui-server', '--image', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}', '--region', 'asia-northeast1', '--service-account', '${_CLOUDRUN_SERVICE_ACCOUNT}', '--set-env-vars', 'FUGA=fuga,HOGE=hoge', '--allow-unauthenticated']
images: ['gcr.io/$PROJECT_ID/${_IMAGE_NAME}']
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE_NAME: webui-node