steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$IMAGE', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$IMAGE']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'webui-server', '--image', 'gcr.io/$PROJECT_ID/$IMAGE', '--region', 'asia-northeast1', '--allow-unauthenticated', '--set-env-vars', '[PORT=1234]']
  images:
  - gcr.io/$PROJECT_ID/#IMAGE